version: "3.8"

services:
  geth:
    image: ethereum/client-go:stable
    container_name: goerli-geth
    restart: unless-stopped
    command:
      --goerli
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=eth,net,web3
      --syncmode=snap
    volumes:
      - geth-data:/root/.ethereum
    ports:
      - "30303:30303"     # P2P networking (TCP)
      - "30303:30303/udp" # P2P networking (UDP)
      - "8545:8545"       # RPC

volumes:
  geth-data:
